### ISSUE TITLE
[BUG] [VALIDAITON] Maka reserve gihapon ang lain na user bisag naa nay ning reserve anang orasa og room

### ISSUE THREAD

**Issue by ghost** [winex01/temporary#29]

**Comment by RebornChieko** [comment]
Example:
Kung naa nay ning reserve og 9:00am sa Room 101 dapat ang lain na user dili na cya ka reserve ana na oras ,unya mu color grey ang 9am/disabled.

**Comment by ghost** [comment]
Example:
Kung naa nay ning reserve og 9:00am sa Room 101 dapat ang lain na user dili na cya ka reserve ana na oras sa ana na room.Pero maka reserve cya og 9am sa pikas na room.Unya mu color grey ang 9am/disabled.

**Comment by ghost** [comment]
Example:
Kung naa nay ning reserve og 9:00am sa Room 101 dapat ang lain na user dili na cya ka reserve ana na oras sa ana na room.Pero maka reserve cya og 9am sa pikas na room.Unya mu color grey ang 9am/disabled.
